# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\betta\Documents\python\pentor\gui\form\ui\pentor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PentorForm(object):
    def setupUi(self, PentorForm):
        PentorForm.setObjectName("PentorForm")
        PentorForm.resize(381, 432)
        self._label_load_key = QtWidgets.QLabel(PentorForm)
        self._label_load_key.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self._label_load_key.setObjectName("_label_load_key")
        self._line_edit_key_path = QtWidgets.QLineEdit(PentorForm)
        self._line_edit_key_path.setGeometry(QtCore.QRect(10, 30, 281, 20))
        self._line_edit_key_path.setObjectName("_line_edit_key_path")
        self._button_load_key = QtWidgets.QPushButton(PentorForm)
        self._button_load_key.setGeometry(QtCore.QRect(300, 30, 75, 23))
        self._button_load_key.setObjectName("_button_load_key")
        self._label_load_image = QtWidgets.QLabel(PentorForm)
        self._label_load_image.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self._label_load_image.setObjectName("_label_load_image")
        self._line_edit_image_path = QtWidgets.QLineEdit(PentorForm)
        self._line_edit_image_path.setGeometry(QtCore.QRect(10, 80, 281, 20))
        self._line_edit_image_path.setObjectName("_line_edit_image_path")
        self._button_load_image = QtWidgets.QPushButton(PentorForm)
        self._button_load_image.setGeometry(QtCore.QRect(300, 80, 75, 23))
        self._button_load_image.setObjectName("_button_load_image")
        self._radio_button_encrypt = QtWidgets.QRadioButton(PentorForm)
        self._radio_button_encrypt.setGeometry(QtCore.QRect(10, 160, 91, 17))
        self._radio_button_encrypt.setObjectName("_radio_button_encrypt")
        self._radio_button_decrypt = QtWidgets.QRadioButton(PentorForm)
        self._radio_button_decrypt.setGeometry(QtCore.QRect(110, 160, 101, 17))
        self._radio_button_decrypt.setObjectName("_radio_button_decrypt")
        self._label_symbols_in_row = QtWidgets.QLabel(PentorForm)
        self._label_symbols_in_row.setGeometry(QtCore.QRect(270, 130, 101, 16))
        self._label_symbols_in_row.setObjectName("_label_symbols_in_row")
        self._spin_box_symbols_in_row = QtWidgets.QSpinBox(PentorForm)
        self._spin_box_symbols_in_row.setGeometry(QtCore.QRect(270, 150, 101, 22))
        self._spin_box_symbols_in_row.setMinimum(1)
        self._spin_box_symbols_in_row.setMaximum(100)
        self._spin_box_symbols_in_row.setObjectName("_spin_box_symbols_in_row")
        self._line_1 = QtWidgets.QFrame(PentorForm)
        self._line_1.setGeometry(QtCore.QRect(10, 110, 361, 16))
        self._line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self._line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self._line_1.setObjectName("_line_1")
        self._line_2 = QtWidgets.QFrame(PentorForm)
        self._line_2.setGeometry(QtCore.QRect(10, 180, 361, 16))
        self._line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self._line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self._line_2.setObjectName("_line_2")
        self._plain_text_edit_text = QtWidgets.QPlainTextEdit(PentorForm)
        self._plain_text_edit_text.setGeometry(QtCore.QRect(10, 210, 361, 181))
        self._plain_text_edit_text.setObjectName("_plain_text_edit_text")
        self._label_text = QtWidgets.QLabel(PentorForm)
        self._label_text.setGeometry(QtCore.QRect(10, 190, 31, 16))
        self._label_text.setObjectName("_label_text")
        self._button_start = QtWidgets.QPushButton(PentorForm)
        self._button_start.setGeometry(QtCore.QRect(10, 400, 75, 23))
        self._button_start.setObjectName("_button_start")
        self._button_about = QtWidgets.QPushButton(PentorForm)
        self._button_about.setGeometry(QtCore.QRect(90, 400, 91, 23))
        self._button_about.setObjectName("_button_about")
        self._label_version = QtWidgets.QLabel(PentorForm)
        self._label_version.setGeometry(QtCore.QRect(350, 410, 31, 20))
        self._label_version.setObjectName("_label_version")
        self._check_box_delete_bad_symbols = QtWidgets.QCheckBox(PentorForm)
        self._check_box_delete_bad_symbols.setGeometry(QtCore.QRect(10, 130, 241, 17))
        self._check_box_delete_bad_symbols.setObjectName("_check_box_delete_bad_symbols")

        self.retranslateUi(PentorForm)
        QtCore.QMetaObject.connectSlotsByName(PentorForm)

    def retranslateUi(self, PentorForm):
        _translate = QtCore.QCoreApplication.translate
        PentorForm.setWindowTitle(_translate("PentorForm", "Pentor"))
        self._label_load_key.setText(_translate("PentorForm", "Ключ"))
        self._button_load_key.setText(_translate("PentorForm", "Выбрать"))
        self._label_load_image.setText(_translate("PentorForm", "Изображение"))
        self._button_load_image.setText(_translate("PentorForm", "Выбрать"))
        self._radio_button_encrypt.setText(_translate("PentorForm", "Зашифровать"))
        self._radio_button_decrypt.setText(_translate("PentorForm", "Расшифровать"))
        self._label_symbols_in_row.setText(_translate("PentorForm", "Символов в строке"))
        self._label_text.setText(_translate("PentorForm", "Текст"))
        self._button_start.setText(_translate("PentorForm", "Начать"))
        self._button_about.setText(_translate("PentorForm", "О программе"))
        self._label_version.setText(_translate("PentorForm", "v1.1"))
        self._check_box_delete_bad_symbols.setText(_translate("PentorForm", "Убрать символы, которых нет в алфавите"))
