# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\betta\Documents\python\pentor\main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 410)
        self._label_key = QtWidgets.QLabel(Form)
        self._label_key.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self._label_key.setObjectName("_label_key")
        self._line_edit_key_path = QtWidgets.QLineEdit(Form)
        self._line_edit_key_path.setGeometry(QtCore.QRect(10, 30, 291, 21))
        self._line_edit_key_path.setObjectName("_line_edit_key_path")
        self._button_get_key_path = QtWidgets.QPushButton(Form)
        self._button_get_key_path.setGeometry(QtCore.QRect(310, 30, 75, 23))
        self._button_get_key_path.setObjectName("_button_get_key_path")
        self._label_image = QtWidgets.QLabel(Form)
        self._label_image.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self._label_image.setObjectName("_label_image")
        self._line_image_path = QtWidgets.QLineEdit(Form)
        self._line_image_path.setGeometry(QtCore.QRect(10, 80, 291, 21))
        self._line_image_path.setObjectName("_line_image_path")
        self._button_get_image_path = QtWidgets.QPushButton(Form)
        self._button_get_image_path.setGeometry(QtCore.QRect(310, 80, 75, 23))
        self._button_get_image_path.setObjectName("_button_get_image_path")
        self._plain_text_edit_text = QtWidgets.QPlainTextEdit(Form)
        self._plain_text_edit_text.setGeometry(QtCore.QRect(10, 180, 371, 191))
        self._plain_text_edit_text.setObjectName("_plain_text_edit_text")
        self._label_text = QtWidgets.QLabel(Form)
        self._label_text.setGeometry(QtCore.QRect(10, 160, 101, 16))
        self._label_text.setObjectName("_label_text")
        self._label_mode = QtWidgets.QLabel(Form)
        self._label_mode.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self._label_mode.setObjectName("_label_mode")
        self._radio_button_enc = QtWidgets.QRadioButton(Form)
        self._radio_button_enc.setGeometry(QtCore.QRect(10, 130, 101, 17))
        self._radio_button_enc.setObjectName("_radio_button_enc")
        self._radio_button_dec = QtWidgets.QRadioButton(Form)
        self._radio_button_dec.setGeometry(QtCore.QRect(110, 130, 101, 17))
        self._radio_button_dec.setObjectName("_radio_button_dec")
        self._label_max_symb_in_row = QtWidgets.QLabel(Form)
        self._label_max_symb_in_row.setGeometry(QtCore.QRect(230, 110, 151, 16))
        self._label_max_symb_in_row.setObjectName("_label_max_symb_in_row")
        self._spin_box_max_symb_in_row = QtWidgets.QSpinBox(Form)
        self._spin_box_max_symb_in_row.setGeometry(QtCore.QRect(230, 130, 151, 21))
        self._spin_box_max_symb_in_row.setObjectName("_spin_box_max_symb_in_row")
        self._button_start = QtWidgets.QPushButton(Form)
        self._button_start.setGeometry(QtCore.QRect(10, 380, 75, 23))
        self._button_start.setObjectName("_button_start")
        self._button_about = QtWidgets.QPushButton(Form)
        self._button_about.setGeometry(QtCore.QRect(100, 380, 91, 23))
        self._button_about.setObjectName("_button_about")
        self._button_exit = QtWidgets.QPushButton(Form)
        self._button_exit.setGeometry(QtCore.QRect(290, 380, 91, 23))
        self._button_exit.setObjectName("_button_exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pentor"))
        self._label_key.setText(_translate("Form", "Ключ"))
        self._button_get_key_path.setText(_translate("Form", "Выбрать"))
        self._label_image.setText(_translate("Form", "Картинка с текстом"))
        self._button_get_image_path.setText(_translate("Form", "Выбрать"))
        self._label_text.setText(_translate("Form", "Текст"))
        self._label_mode.setText(_translate("Form", "Режим"))
        self._radio_button_enc.setText(_translate("Form", "Зашифровать"))
        self._radio_button_dec.setText(_translate("Form", "Расшифровать"))
        self._label_max_symb_in_row.setText(_translate("Form", "Максимум символов в строке"))
        self._button_start.setText(_translate("Form", "Начать"))
        self._button_about.setText(_translate("Form", "О приложении"))
        self._button_exit.setText(_translate("Form", "Выйти"))
